server:
  port: 8000

spring:
  application:
    name: spring-boot-demo

#  profiles:
#    active: development
#
#  security:
#    user:
#      name: test
#      password: 123456

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 2021@root
  #datasource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  config: classpath:logback.xml
  level:
    root: INFO
